### ISSUE TITLE
Error of log when run fail2ban-client reload honeypot

### ISSUE THREAD

**Issue by hectorRNS** [VedranIteh/fail2ban-ssh-honeypot#4]
**I have this error:**
2021-04-15 15:11:09,555 fail2ban                [10699]: ERROR   Failed during configuration: Have not found any log file for honeypot jail

**When run fail2ban-client reload honeypot**

**Comment by curzon01** [comment]
`touch /var/log/messages`

**Comment by VedranIteh** [comment]
You might not be using a distro that logs iptables (or other system events) into /var/log/messages file, change your log path in  jail.local accordingly.

**Comment by curzon01** [comment]
the error message is clear here, the log file is missing, it's not related any content

**Comment by rafamerino** [comment]
You have to restart fail2ban service BEFORE fail2ban-client reload honeypot. So:

**3.- add this code block to your jail.local**
(blah blah blah)

**4.- copy honeypot.conf to /etc/fail2ban/filter.d/honeypot.conf**

**5.- Restart fail2ban service** <---- THIS IS NOT IN THE README @VedranIteh 
`service fail2ban restart`

**6.- run fail2ban-client reload honeypot**
`fail2ban-client reload honeypot`
OK

**7.- Check jail**
`fail2ban-client status honeypot`
Status for the jail: honeypot
|- Filter
|  |- Currently failed: 0
|  |- Total failed:     2
|  - File list:        /var/log/messages
 |- Actions
  |- Currently banned: 2
   |- Total banned:     2
   |- Banned IP list:   159.203.x.x 192.241.x.x

**Comment by VedranIteh** [comment]
with reload you pull only the new jail configuration if you do restart you will unban all other jails too and restart them. I know the "RE-load" doesn't sound like it will read the new jails but it works. Feature or a bug i don't know.

I personally avoid restarting because I have recidive jail set up which holds 1000's of IPs on long term ban.

**Comment by rafamerino** [comment]
> 

If you don't restart the fail2ban **SERVICE** -not jail- (_service fail2ban restart_), you CAN NOT enable jail honeypot (step 6 with your reload > _fail2ban-client reload honeypot_ ) 

Restart fail2ban service != reload fail2ban jail

**Comment by VedranIteh** [comment]
cool thx for info. definitely the right way to do. changed the readme accordingly.
